# Setup
title:               Startupers
tagline:             We save you time
url:                 http://www.startupers.io
analytics_id:        UA-5126579-44

# About/contact
author:
  name:                Startupers
  email:               "todo@startupers.io" # email here 
  avatar:              img/logo.png 
  profile-pic:         img/logo-black.png


# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Startupers
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"
      